jwt:
  secret: 'dhfjdhsjfkhadsfhakjfkadhskjfhkjadhsjfhads4564hd3fg4hfgdfg'

server:
  port: 8080
#  error:
#    whitelabel:
#      enabled: false

spring:
  datasource:
    password: 518641
    url: jdbc:postgresql://localhost:5432/supportportal
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false
